name: CLI Nightlies (Windows)
on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_build:
    name: Test CLI
    timeout-minutes: 20
    runs-on: ["windows-latest"]
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run Tests
        env:
          SIMVUE_URL: ${{ secrets.SIMVUE_URL }}
          SIMVUE_TOKEN: ${{ secrets.SIMVUE_TOKEN }}
        run: |
          uv sync --all-groups --python 3.14
          uv run --python 3.14 pytest -x -c /dev/null -p no:warnings -v
