name: CLI Nightlies (Ubuntu)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_build:
    name: Test CLI
    timeout-minutes: 20
    runs-on: ["ubuntu-latest"]
    strategy:
      matrix:
        python_version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run Tests
        env:
          SIMVUE_URL: ${{ secrets.SIMVUE_URL }}
          SIMVUE_TOKEN: ${{ secrets.SIMVUE_TOKEN }}
        run: |
          uv sync --all-groups
          uv run --python ${{ matrix.python_version }} \
          pytest -x -c /dev/null -p no:warnings -v
